name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install black
      - name: Run black
        run: |
          black --check --diff aws_cdk_config

  validate-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install poetry
      - name: Check lock file
        run: poetry check --lock

  pytest:
    needs: validate-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Pytest
        run: |
          poetry run pytest

  build:
    needs:
      - pytest
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Build and Upload
        uses: JRubics/poetry-publish@v1.17
        with:
          pypi_token: ${{secrets.PYPI_TOKEN}}

  gen-docs:
    needs:
      - pytest
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser more-itertools typeguard
      - name: Sphinx build
        run: |
          cd docs
          make html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
